In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = df.drop('sales' , axis=1)
y = df['sales']

In [4]:
from sklearn.preprocessing import PolynomialFeatures

In [5]:
poly_conv = PolynomialFeatures(degree = 3 , include_bias = False)

In [6]:
X_poly = poly_conv.fit_transform(X)

In [7]:
X.shape

(200, 3)

In [8]:
X_poly.shape

(200, 19)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train , X_test , y_train , y_test = train_test_split(X_poly , y , test_size = 0.2 , random_state = 53)

In [11]:
X_train.shape

(160, 19)

In [12]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [13]:
scaler = StandardScaler()
#scaler = MinMaxScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Ridge Model

In [16]:
from sklearn.linear_model import Ridge

In [17]:
ridge = Ridge(alpha = 10)

In [18]:
ridge.fit(X_train , y_train)

Ridge(alpha=10)

In [19]:
y_pred = ridge.predict(X_test)

In [20]:
from sklearn.metrics import r2_score , mean_absolute_error , mean_squared_error

In [21]:
r2 = r2_score(y_test , y_pred)
mae = mean_absolute_error(y_test , y_pred)
rmse = mean_squared_error(y_test , y_pred) ** 0.5

In [22]:
rmse

0.7240855313266406

In [23]:
ridge.coef_

array([ 8.39657261e-02,  1.12283544e-02,  7.28415721e-03, -4.11393825e-04,
        1.59316351e-03, -2.50446025e-04, -1.60221106e-03,  1.48308257e-03,
       -3.69994460e-05,  7.13431879e-07, -1.57757828e-06,  8.31817500e-07,
        3.11214639e-06, -5.02394554e-06,  8.54089914e-07,  1.75565147e-05,
       -5.97076686e-06, -3.46356697e-06, -6.87246765e-07])

In [24]:
from sklearn.linear_model import RidgeCV

In [25]:
ridge_cv = RidgeCV(alphas=(0.1,1,10) , scoring='neg_root_mean_squared_error')

In [26]:
ridge_cv.fit(X_train , y_train)

RidgeCV(alphas=(0.1, 1, 10), scoring='neg_root_mean_squared_error')

In [27]:
ridge_cv.best_score_

-0.5937685243497502

In [28]:
ridge_cv.alpha_

10.0

In [29]:
from sklearn.metrics import SCORERS

In [30]:
SCORERS.keys() # all scoring metrics.

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_s

In [31]:
y_pred = ridge_cv.predict(X_test)

In [32]:
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)

In [33]:
rmse

0.5254090819805524

In [34]:
ridge_cv.coef_

array([ 8.39657261e-02,  1.12283544e-02,  7.28415721e-03, -4.11393609e-04,
        1.59316368e-03, -2.50446132e-04, -1.60221103e-03,  1.48308257e-03,
       -3.69995270e-05,  7.13975169e-07, -1.54303052e-06,  8.01606802e-07,
        3.11997792e-06, -5.02271996e-06,  8.40336725e-07,  1.75578457e-05,
       -5.97058374e-06, -3.46513889e-06, -6.94645450e-07])

# Lasso Model

In [35]:
from sklearn.linear_model import Lasso , LassoCV

In [36]:
# lasso_cv = LassoCV(eps = 0.01 , n_alphas = 100 , cv = 5 , max_iter = 100000) # lasso_cv = LassoCV(alphas = np.linspace(0,01,10,100) , cv = 5)

In [37]:
lasso_cv = LassoCV(alphas = np.linspace(0.01,10,1000) , cv = 5 , max_iter = 100000)

In [38]:
lasso_cv.fit(X_train , y_train)

LassoCV(alphas=array([ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,
        0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,
        0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,
        0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,  0.36,
        0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,  0.45,
        0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,  0.54,
        0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,  0.63,
        0.64,  0.65,  0.66,  0.67...
        9.28,  9.29,  9.3 ,  9.31,  9.32,  9.33,  9.34,  9.35,  9.36,
        9.37,  9.38,  9.39,  9.4 ,  9.41,  9.42,  9.43,  9.44,  9.45,
        9.46,  9.47,  9.48,  9.49,  9.5 ,  9.51,  9.52,  9.53,  9.54,
        9.55,  9.56,  9.57,  9.58,  9.59,  9.6 ,  9.61,  9.62,  9.63,
        9.64,  9.65,  9.66,  9.67,  9.68,  9.69,  9.7 ,  9.71,  9.72,
        9.73,  9.74,  9.75,  9.76,  9.77,  9.78,  9.79,  9.8 ,  9.81,
        9.82,  9.83,  9.84,  9.85,  9.86,  9.87,  9.88,  9.89,  9.9 ,
        9.91,  9.92,  9.93,  9.94,  9.95,  9.96,  9.97,  9.98,  9.99,
       10.  ]),
        cv=5, max_iter=100000)

In [39]:
lasso_cv.alpha_

0.12

In [40]:
lasso_cv.coef_

array([ 8.01432321e-02,  0.00000000e+00,  0.00000000e+00, -3.93770684e-04,
        1.65327928e-03, -2.12440079e-04, -1.38868454e-03,  1.66304730e-03,
        0.00000000e+00,  6.86459159e-07, -1.68797519e-06,  7.80776680e-07,
        2.84529100e-06, -5.47093952e-06,  8.03785810e-07,  1.56650131e-05,
       -7.38284409e-06, -3.59848028e-06, -8.32750317e-07])

In [41]:
y_pred = lasso_cv.predict(X_test)

In [42]:
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)

In [43]:
r2

0.9803987438574662

In [44]:
mae

0.47672479119202676

In [45]:
rmse

0.5339926108084159

# Elastic Net Model

In [46]:
from sklearn.linear_model import ElasticNet , ElasticNetCV

In [47]:
els = ElasticNetCV(l1_ratio = np.linspace(0.01,1,100) , alphas = np.linspace(0.01,1,100) , max_iter = 100000)

In [48]:
# els = ElasticNetCV(l1_ratio= [0.1,0.5,0.7,0.9,0.95,0.99,1],
#                    eps = 0.001 , n_alphas=100 , max_iter = 100000 )

In [49]:
els.fit(X_train,y_train)

ElasticNetCV(alphas=array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66...
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ]),
             max_iter=100000)

In [50]:
els.alpha_

0.12

In [51]:
els.l1_ratio_

0.97

In [52]:
y_pred = els.predict(X_test)

In [53]:
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)

In [54]:
r2

0.9803980318519712

In [55]:
mae

0.47681257599785826

In [56]:
rmse

0.5340120078139173

In [ ]:
# Done